parameters:
    database_driver: pdo_mysql
    database_host: localhost
    database_port: null
    database_name: fogan
    database_user: root
    database_password: developer
    mailer_transport: smtp
    mailer_host: localhost
    mailer_user: null
    mailer_password: null
    locale: en
    secret: 04aaf9b55796109edc1828df024537b559bf9ea4
    database_path: null
