<?php

namespace Jalis\FoganBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AnimalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnimalRepository extends EntityRepository
{
}
